import { Inter } from "next/font/google";
import { Aleo } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const aleo = Aleo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aleo.className}>{children}</body>
    </html>
  );
}
